# Generated by Django 6.0 on 2025-12-17 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Desarrollador Python', max_length=200)),
                ('empresa', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('region', models.CharField(choices=[('AP', 'Arica y Parinacota'), ('TA', 'Tarapacá'), ('AN', 'Antofagasta'), ('AT', 'Atacama'), ('CO', 'Coquimbo'), ('VA', 'Valparaíso'), ('RM', 'Metropolitana de Santiago'), ('BI', 'Biobío'), ('AR', 'Araucanía'), ('LS', 'Los Lagos'), ('AI', 'Aysén'), ('MA', 'Magallanes'), ('NB', 'Ñuble'), ('LR', 'Los Ríos')], default='RM', max_length=2)),
                ('experiencia', models.CharField(choices=[('JR', 'Recién Egresado / Junior'), ('SSR', 'Semi Senior (2-5 años)'), ('SR', 'Senior (+5 años)')], default='JR', max_length=3)),
                ('es_destacado', models.BooleanField(default=False, verbose_name='¿Es anuncio pagado?')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
