# Generated by Django 6.0 on 2025-12-17 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='publicada',
            field=models.BooleanField(default=False, verbose_name='¿Visible en la web?'),
        ),
    ]
