# Generated by Django 6.0 on 2025-12-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0002_ofertalaboral_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='tipo',
            field=models.CharField(choices=[('PRO', 'Profesional / Universitario'), ('OFI', 'Oficio / Técnico / Operario')], default='OFI', max_length=3, verbose_name='Tipo de Empleo'),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
