# Generated by Django 6.0 on 2025-12-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0003_ofertalaboral_tipo_alter_ofertalaboral_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('especialidad', models.CharField(help_text='Ej: Electricista Certificado, Abogado Laboral...', max_length=100)),
                ('tipo', models.CharField(choices=[('PRO', 'Profesional / Universitario'), ('OFI', 'Oficio / Técnico / Operario')], default='OFI', max_length=3, verbose_name='Perfil')),
                ('region', models.CharField(choices=[('AP', 'Arica y Parinacota'), ('TA', 'Tarapacá'), ('AN', 'Antofagasta'), ('AT', 'Atacama'), ('CO', 'Coquimbo'), ('VA', 'Valparaíso'), ('RM', 'Metropolitana de Santiago'), ('BI', 'Biobío'), ('AR', 'Araucanía'), ('LS', 'Los Lagos'), ('AI', 'Aysén'), ('MA', 'Magallanes'), ('NB', 'Ñuble'), ('LR', 'Los Ríos')], default='RM', max_length=2)),
                ('experiencia', models.CharField(choices=[('JR', 'Recién Egresado / Junior'), ('SSR', 'Semi Senior (2-5 años)'), ('SR', 'Senior (+5 años)')], default='JR', max_length=3)),
                ('telefono', models.CharField(help_text='Ej: +569 1234 5678', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('presentacion', models.TextField(help_text='Cuenta brevemente qué haces y qué buscas.', verbose_name='Breve presentación')),
                ('publicado', models.BooleanField(default=False, verbose_name='¿Visible?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
