# Generated by Django 6.0 on 2025-12-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0004_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='telefono',
            field=models.CharField(default='', help_text='Ej: 56912345678', max_length=20, verbose_name='Teléfono de Contacto'),
            preserve_default=False,
        ),
    ]
