# Generated by Django 6.0 on 2025-12-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0005_ofertalaboral_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresas', verbose_name='Logo de la empresa'),
        ),
    ]
