# Generated by Django 6.0 on 2025-12-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0006_ofertalaboral_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='presentacion',
            field=models.TextField(verbose_name='Breve presentación'),
        ),
    ]
