# Generated by Django 6.0 on 2025-12-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0007_alter_candidato_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
