# Generated by Django 6.0 on 2025-12-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0008_ofertalaboral_visitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email para postular (Opcional)'),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='etiquetas',
            field=models.CharField(blank=True, help_text='Separa con comas. Ej: Excel, Inglés, Python', max_length=200, verbose_name='Etiquetas / Habilidades'),
        ),
    ]
