# Generated by Django 6.0 on 2025-12-18 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0010_noticia'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs_candidatos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Subir CV (PDF)'),
        ),
    ]
