# Generated by Django 6.0 on 2025-12-18 02:15

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0012_suscriptor_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='comentario',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='estrellas',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
