# Generated by Django 6.0 on 2025-12-18 02:19

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0013_ofertalaboral_token_alter_valoracion_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='fecha_cierre',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Cierre de postulaciones'),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='modalidad',
            field=models.CharField(choices=[('PRE', 'Presencial 🏢'), ('HIB', 'Híbrido 🌗'), ('REM', '100% Remoto 🏠')], default='PRE', max_length=3, verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='sueldo',
            field=models.PositiveIntegerField(blank=True, help_text="Deja en 0 si es 'A convenir'", null=True, verbose_name='Sueldo Líquido (Opcional)'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs_candidatos', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='especialidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='presentacion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='tipo',
            field=models.CharField(choices=[('PRO', 'Profesional / Universitario'), ('OFI', 'Oficio / Técnico / Operario')], default='OFI', max_length=3),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email contacto'),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='es_destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresas'),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='telefono',
            field=models.CharField(help_text='Ej: 56912345678', max_length=20, verbose_name='Teléfono'),
        ),
    ]
