# Generated by Django 6.0 on 2025-12-18 02:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0014_ofertalaboral_fecha_cierre_ofertalaboral_modalidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='empresa_verificada',
            field=models.BooleanField(default=False, verbose_name='¿Empresa Verificada? (Check Azul)'),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='fecha_cierre',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Cierre postulaciones'),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='sueldo',
            field=models.PositiveIntegerField(blank=True, help_text="Deja en 0 si es 'A convenir'", null=True, verbose_name='Sueldo Líquido'),
        ),
    ]
