# Generated by Django 6.0 on 2025-12-18 21:27

import django.core.validators
import empleos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0015_ofertalaboral_empresa_verificada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to=empleos.models.renombrar_archivo, validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=empleos.models.renombrar_logo),
        ),
    ]
