# Generated by Django 6.0 on 2025-12-18 22:22

import django.db.models.deletion
import django.utils.timezone
import empleos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0016_alter_candidato_cv_alter_ofertalaboral_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='tipo',
        ),
        migrations.AddField(
            model_name='candidato',
            name='disponibilidad',
            field=models.CharField(default='Inmediata', help_text='Ej: Inmediata, 1 mes', max_length=50),
        ),
        migrations.AddField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=empleos.models.renombrar_foto, verbose_name='Foto Perfil'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='Perfil LinkedIn'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='pretension_renta',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Renta Esperada'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='rubro',
            field=models.CharField(choices=[('ADM', 'Administración y Oficina 📁'), ('AGR', 'Agroindustria / Forestal 🌲'), ('CONS', 'Construcción e Inmobiliaria 🏗️'), ('EDU', 'Educación y Capacitación 🎓'), ('GAS', 'Gastronomía y Turismo 🍽️'), ('LOG', 'Logística, Bodega y Transporte 🚚'), ('MIN', 'Minería e Industria ⛏️'), ('SAL', 'Salud y Medicina 🏥'), ('TEC', 'Tecnología e Informática 💻'), ('VTA', 'Ventas y Retail 🛒'), ('OFI', 'Oficios Varios 🔧'), ('OTR', 'Otros Servicios')], default='OTR', max_length=4, verbose_name='Área'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='titular',
            field=models.CharField(default='', help_text='Ej: Ingeniero Civil, Maestro Pintor...', max_length=100, verbose_name='Título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='experiencia',
            field=models.CharField(choices=[('JR', 'Junior / Recién Egresado'), ('SSR', 'Semi Senior (2-5 años)'), ('SR', 'Senior (+5 años)')], default='JR', max_length=3),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='presentacion',
            field=models.TextField(verbose_name='Sobre mí'),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='empresa_verificada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='experiencia',
            field=models.CharField(choices=[('JR', 'Junior / Recién Egresado'), ('SSR', 'Semi Senior (2-5 años)'), ('SR', 'Senior (+5 años)')], default='JR', max_length=3),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='fecha_cierre',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='modalidad',
            field=models.CharField(choices=[('PRE', 'Presencial 🏢'), ('HIB', 'Híbrido 🌗'), ('REM', '100% Remoto 🏠')], default='PRE', max_length=3),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='sueldo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='tipo',
            field=models.CharField(choices=[('PRO', 'Profesional'), ('OFI', 'Técnico / Oficio')], default='OFI', max_length=3),
        ),
    ]
