# Generated by Django 6.0 on 2025-12-18 22:55

import django.db.models.deletion
import empleos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0017_remove_candidato_especialidad_remove_candidato_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('palabra_clave', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('AP', 'Arica y Parinacota'), ('TA', 'Tarapacá'), ('AN', 'Antofagasta'), ('AT', 'Atacama'), ('CO', 'Coquimbo'), ('VA', 'Valparaíso'), ('RM', 'Metropolitana de Santiago'), ('BI', 'Biobío'), ('AR', 'Araucanía'), ('LS', 'Los Lagos'), ('AI', 'Aysén'), ('MA', 'Magallanes'), ('NB', 'Ñuble'), ('LR', 'Los Ríos')], max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='disponibilidad',
            field=models.CharField(default='Inmediata', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=empleos.models.renombrar_foto),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='presentacion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='pretension_renta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='rubro',
            field=models.CharField(choices=[('ADM', 'Administración y Oficina 📁'), ('AGR', 'Agroindustria / Forestal 🌲'), ('CONS', 'Construcción e Inmobiliaria 🏗️'), ('EDU', 'Educación y Capacitación 🎓'), ('GAS', 'Gastronomía y Turismo 🍽️'), ('LOG', 'Logística, Bodega y Transporte 🚚'), ('MIN', 'Minería e Industria ⛏️'), ('SAL', 'Salud y Medicina 🏥'), ('TEC', 'Tecnología e Informática 💻'), ('VTA', 'Ventas y Retail 🛒'), ('OFI', 'Oficios Varios 🔧'), ('OTR', 'Otros Servicios')], default='OTR', max_length=4),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='titular',
            field=models.CharField(max_length=100),
        ),
    ]
