# Generated by Django 6.0 on 2025-12-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0018_alertaempleo_ofertalaboral_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalaboral',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ej: 360 horas, 3 meses', max_length=100, null=True, verbose_name='Duración (Solo Prácticas)'),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='tipo',
            field=models.CharField(choices=[('PRO', 'Profesional'), ('OFI', 'Técnico / Oficio'), ('PRA', 'Práctica Profesional 🎓')], default='OFI', max_length=3),
        ),
    ]
