# Generated by Django 6.0 on 2025-12-18 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0019_ofertalaboral_duracion_alter_ofertalaboral_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje breve (Carta de presentación)')),
                ('estado', models.CharField(choices=[('ENV', 'Enviada a la empresa d'), ('VIS', 'Visto por el reclutador 👀'), ('INT', 'En Proceso / Entrevista 🤝'), ('NO', 'Descartado ❌')], default='ENV', max_length=3)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.candidato')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='empleos.ofertalaboral')),
            ],
            options={
                'unique_together': {('oferta', 'candidato')},
            },
        ),
    ]
