# Generated by Django 6.0 on 2025-12-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0020_postulacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='mensaje',
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='duracion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Duración (Solo Prácticas)'),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('ENV', 'Enviada 📩'), ('VIS', 'Visto 👀'), ('INT', 'Entrevista 🤝'), ('NO', 'Descartado ❌')], default='ENV', max_length=3),
        ),
    ]
