# Generated by Django 6.0 on 2025-12-18 23:27

import django.db.models.deletion
import empleos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0021_remove_postulacion_mensaje_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=empleos.models.renombrar_logo)),
                ('banner', models.ImageField(blank=True, help_text='Imagen ancha de portada (1200x300)', null=True, upload_to='banners_empresas/')),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField(help_text='Cultura, misión, beneficios...', verbose_name='Sobre nosotros')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('FRA', 'Fraude / Estafa ⚠️'), ('DIS', 'Discriminación 🚫'), ('SEX', 'Contenido Sexual / Inapropiado 🔞'), ('REP', 'Oferta Repetida / Spam 🔁'), ('OTR', 'Otro motivo')], max_length=3)),
                ('detalle', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleos.ofertalaboral')),
            ],
        ),
    ]
