# Generated by Django 6.0 on 2025-12-19 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0022_perfilempresa_reporteoferta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempresa',
            name='es_premium',
            field=models.BooleanField(default=False, verbose_name='¿Es Premium? 💎'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='duracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners_empresas/'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='reporteoferta',
            name='motivo',
            field=models.CharField(max_length=3),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('enlace', models.CharField(blank=True, max_length=200, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
