# Generated by Django 6.0 on 2025-12-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0023_perfilempresa_es_premium_alter_candidato_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempresa',
            name='es_destacada',
            field=models.BooleanField(default=False, verbose_name='¿Destacar en Home? 🌟'),
        ),
    ]
