# Generated by Django 6.0 on 2025-12-20 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0024_perfilempresa_es_destacada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='disponibilidad',
            field=models.CharField(blank=True, default='Inmediata', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='experiencia',
            field=models.CharField(blank=True, choices=[('JR', 'Junior / Recién Egresado'), ('SSR', 'Semi Senior (2-5 años)'), ('SR', 'Senior (+5 años)')], default='JR', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='presentacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='region',
            field=models.CharField(blank=True, choices=[('AP', 'Arica y Parinacota'), ('TA', 'Tarapacá'), ('AN', 'Antofagasta'), ('AT', 'Atacama'), ('CO', 'Coquimbo'), ('VA', 'Valparaíso'), ('RM', 'Metropolitana de Santiago'), ('BI', 'Biobío'), ('AR', 'Araucanía'), ('LS', 'Los Lagos'), ('AI', 'Aysén'), ('MA', 'Magallanes'), ('NB', 'Ñuble'), ('LR', 'Los Ríos')], default='RM', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='rubro',
            field=models.CharField(blank=True, choices=[('ADM', 'Administración y Oficina 📁'), ('AGR', 'Agroindustria / Forestal 🌲'), ('CONS', 'Construcción e Inmobiliaria 🏗️'), ('EDU', 'Educación y Capacitación 🎓'), ('GAS', 'Gastronomía y Turismo 🍽️'), ('LOG', 'Logística, Bodega y Transporte 🚚'), ('MIN', 'Minería e Industria ⛏️'), ('SAL', 'Salud y Medicina 🏥'), ('TEC', 'Tecnología e Informática 💻'), ('VTA', 'Ventas y Retail 🛒'), ('OFI', 'Oficios Varios 🔧'), ('OTR', 'Otros Servicios')], default='OTR', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='titular',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='experiencia',
            field=models.CharField(blank=True, choices=[('JR', 'Junior / Recién Egresado'), ('SSR', 'Semi Senior (2-5 años)'), ('SR', 'Senior (+5 años)')], default='JR', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='fecha_cierre',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='modalidad',
            field=models.CharField(blank=True, choices=[('PRE', 'Presencial 🏢'), ('HIB', 'Híbrido 🌗'), ('REM', '100% Remoto 🏠')], default='PRE', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='region',
            field=models.CharField(blank=True, choices=[('AP', 'Arica y Parinacota'), ('TA', 'Tarapacá'), ('AN', 'Antofagasta'), ('AT', 'Atacama'), ('CO', 'Coquimbo'), ('VA', 'Valparaíso'), ('RM', 'Metropolitana de Santiago'), ('BI', 'Biobío'), ('AR', 'Araucanía'), ('LS', 'Los Lagos'), ('AI', 'Aysén'), ('MA', 'Magallanes'), ('NB', 'Ñuble'), ('LR', 'Los Ríos')], default='RM', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PRO', 'Profesional'), ('OFI', 'Técnico / Oficio'), ('PRA', 'Práctica Profesional 🎓')], default='OFI', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='ofertalaboral',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='es_destacada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='es_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
