# Generated by Django 6.0 on 2025-12-20 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0025_alter_candidato_disponibilidad_alter_candidato_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilempresa',
            name='es_destacada',
            field=models.BooleanField(default=False, verbose_name='¿Destacar en Home? 🌟'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='es_premium',
            field=models.BooleanField(default=False, verbose_name='¿Es Premium? 💎'),
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('fecha_pregunta', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='empleos.ofertalaboral')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
