# Generated by Django 6.0 on 2025-12-21 11:52

import django.core.validators
import empleos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleos', '0027_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_candidatos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi']), empleos.models.validar_video]),
        ),
        migrations.AddField(
            model_name='ofertalaboral',
            name='wsp_activo',
            field=models.BooleanField(default=False, verbose_name='¿Contactar por WhatsApp?'),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='es_destacada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='es_premium',
            field=models.BooleanField(default=False),
        ),
    ]
